"""Add question history table

Revision ID: 427a05b3b3c9
Revises: 0002
Create Date: 2026-05-02 17:03:08.059197

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '427a05b3b3c9'
down_revision: Union[str, None] = '0002'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('question_history',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('subject_id', sa.UUID(), nullable=True),
    sa.Column('question_text', sa.Text(), nullable=False),
    sa.Column('answer_text', sa.Text(), nullable=True),
    sa.Column('retrieved_chunk_ids', postgresql.ARRAY(sa.UUID()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_question_history_subject_id'), 'question_history', ['subject_id'], unique=False)
    op.create_index(op.f('ix_question_history_user_id'), 'question_history', ['user_id'], unique=False)
    op.drop_index(op.f('ix_text_blocks_unembedded'), table_name='text_blocks', postgresql_where='(embedded_at IS NULL)')
    op.create_index(op.f('ix_text_blocks_embedded_at'), 'text_blocks', ['embedded_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_text_blocks_embedded_at'), table_name='text_blocks')
    op.create_index(op.f('ix_text_blocks_unembedded'), 'text_blocks', ['document_id'], unique=False, postgresql_where='(embedded_at IS NULL)')
    op.drop_index(op.f('ix_question_history_user_id'), table_name='question_history')
    op.drop_index(op.f('ix_question_history_subject_id'), table_name='question_history')
    op.drop_table('question_history')
    # ### end Alembic commands ###
